[project]
name = "pysterize"
version = "0.1.0"
description = "Command line posterizer tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymupdf>=1.24.10",
]

[project.scripts]
pysterize = "pysterize:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
